### ISSUE TITLE
AER cards not available

### ISSUE THREAD

**Issue by Cyantoo** [Dryvnt/proxygen#17]
Hey,

I love your work and I always use your proxies when testing. When will AER cards be available?

Thanks in advance.

**Comment by Dryvnt** [comment]
I haven't been playing MTG for months, so I'm not super active in the community.

This issue made me check [mtgjson](http://mtgjson.com/) and it seems that they have updated to include AER.

I've updated the program running on the server; AER should now be available.

Thank you for your interest and question!
