### ISSUE TITLE
Can't Input Cards from Newest Set

### ISSUE THREAD

**Issue by NeoMobius** [Dryvnt/proxygen#18]
I'm receiving an error message (Invalid card name: "XYZ Card") for cards I input in the  site.
This only applies to the newest card set (Dominaria released April 27, 2018).
The card set seems to have been updated on mtgjson.
Please let me know if there are any workarounds.

**Comment by Dryvnt** [comment]
I have to manually re-download and re-compile every set release. I forgot that I did not do it for Dominaria.

This is something I want to completely automate when I do a complete rewrite of this project. I should hopefully get to do that in a few months.

Thank you for bringing this to my attention. Site should now work as advertised.
