### ISSUE TITLE
RNA not available

### ISSUE THREAD

**Issue by brian-mcdonald** [Dryvnt/proxygen#19]
Looks like RNA has not been loaded yet. If it's too soon for that, sorry for jumping the gun.

_Invalid card name: "Deputy of Detention"_

Thanks

**Comment by Dryvnt** [comment]
Yeah, this is a problem. It seems mtgjson has changed their data format. This means I have to go actually change the code of this program, which is going to be a big mess for various reasons.

All things considered, I'll probably have to do something akin to a full rewrite. This sucks. Stay tuned.

**Comment by Dryvnt** [comment]
I have rewritten the entire project and released it on (proxygen.xyz)[https://proxygen.xyz]. Thank you for bringing the fact that this rickety pile of code couldn't chug it anymore to my attention. :)
